---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: https://www.goodreads.com/review/list_rss/{{ gr_account_number }}?shelf={{ shelf }}
polling_headers: ''
polling_body: 
id: 168273
custom_fields:
- keyname: ignore
  name: About This Plugin
  field_type: author_bio
  description: Show your Goodreads shelves with a large book cover on the left and metadata on the right.
  github_url: https://github.com/Wandmalfarbe/trmnl-goodreads
- keyname: gr_account_number
  name: Goodreads Account Number
  field_type: string
  description: Go to your Goodreads profile and put the numbers from the URL here. For example put 26367680 when your profile URL is https://www.goodreads.com/user/show/26367680.
  placeholder: 26367680
- keyname: shelf
  name: Shelf
  field_type: select
  options:
  - Want to Read: to-read
  - Currently Reading: currently-reading
  - Read: read
  default: read
  description: The shelf you want to display.
- keyname: layout
  name: Layout
  field_type: select
  options:
  - '1 Book: Image Left, Metadata Right': large
  - Cover Only: cover_only
  default: large
  description: The layout for your shelf.
- keyname: layout_number_of_books
  name: Number of Books
  field_type: number
  placeholder: 3
  default: 3
  description: 'The number of books to display. There is a maximum number of books that can be displayed depending on the size: full = 3, half_horizontal = 6, quadrant = 3, half_vertical = 2. Any value higher gets clamped to this maximum number.<br><br><b>This option only has an effect when "Layout" is "Cover Only"</b>'
name: Goodreads
refresh_interval: 1440
